# Generated by Django 2.2.11 on 2020-07-12 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200711_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 8, 27, 17, 385985, tzinfo=utc)),
        ),
    ]
